services:
  frontend-1:
    image: muazhari/social-media-frontend-1:latest
    build:
      context: ${FRONTEND_1_PATH}
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_1_PORT}:3000"
    env_file:
      - ./.env
    depends_on:
      - backend-1
  backend-1:
    image: muazhari/social-media-backend-1:latest
    build:
      context: ${BACKEND_1_PATH}
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_1_PORT}:8080"
    env_file:
      - ./.env
    depends_on:
      - datastore-1
      - datastore-2
      - datastore-3
  datastore-1:
    image: redis/redis-stack-server:latest
    ports:
      - "${DATASTORE_1_PORT}:6379"
    environment:
      - REDIS_ARGS=--requirepass ${DATASTORE_2_PASSWORD}
  datastore-2:
    image: postgis/postgis:latest
    ports:
      - "${DATASTORE_2_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATASTORE_2_USER}
      POSTGRES_PASSWORD: ${DATASTORE_2_PASSWORD}
      POSTGRES_DB: ${DATASTORE_2_DATABASE}
      PGDATA: /var/lib/pg_data
    volumes:
      - ./migration-2.sql:/docker-entrypoint-initdb.d/migration-2.sql
  datastore-3:
    image: postgis/postgis:latest
    ports:
      - "${DATASTORE_3_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATASTORE_3_USER}
      POSTGRES_PASSWORD: ${DATASTORE_3_PASSWORD}
      POSTGRES_DB: ${DATASTORE_3_DATABASE}
      PGDATA: /var/lib/pg_data
    volumes:
      - ./migration-3.sql:/docker-entrypoint-initdb.d/migration-3.sql