# yaml-language-server: $schema=https://raw.githubusercontent.com/wundergraph/cosmo/main/router/pkg/config/config.schema.json

version: "1"

log_level: "debug"

headers:
  all:
    request:
      - op: "propagate"
        named: "Authorization"

authentication:
  jwt:
    jwks:
      - url: "${AUTH_JWKS_URL}"
    header_name: "Authorization"
    header_value_prefix: "Bearer"

events:
  providers:
    kafka:
      - id: "default"
        brokers:
          - "${DATASTORE_5_HOST}:${DATASTORE_5_PORT}"
  